### ISSUE TITLE
ScrollState interaction flows are not producing values. 

### ISSUE THREAD

**Issue by morale3232** [chihsuanwu/compose-free-scroll#2]
I am testing out some behaviors with the free scroll, and it looks great. I am having issues with the scroll states' interaction flows, and cannot get the values to come through like they do with the native vertical and horizontal scroll states. Here is a screenshot showing what I'm trying to do, which is just log the values as the tables are scrolled. I know that both of the `collectLatest` calls are made, but no logs are ever printed. Is this supposed to work or is there something else I need to do to enable those flows? 

<img width="848" alt="ScrollStateCode" src="https://github.com/user-attachments/assets/78eeb09e-71f0-402d-bff8-12807a9c3ed9">

**Comment by chihsuanwu** [comment]
Hi, I realized that this behavior is a current limitation of the freeScroll implementation. The scroll states (horizontalScrollState and verticalScrollState) are updated by custom gestures rather than the native horizontalScroll or verticalScroll, which means interactionSource.interactions is not triggered as expected.

After a brief look, I found that there isn’t a simple way to fix this issue. Since InteractionSource is not mutable, it’s not possible to emit events from within the gesture detection logic. As a result, I currently don’t have a good solution for this problem.
